workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "stable"
      when: always
    - when: never

stages:
  - test
  - documentation
  - copy

testing-project:
  stage: test
  image: ubuntu:latest
  variables: 
    GIT_DEPTH: 0
  before_script:
    - apt-get update -y && apt-get install -y python3 python3-pip python3-venv
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - pytest --reuse-db
  

sphinx-documentation:
  stage: documentation
  image: ubuntu:latest
  variables:
    GIT_DEPTH: 0
  before_script:
    - apt-get update -y && apt-get install -y python3 python3-pip
  script:
    - pip3 install sphinx sphinx_rtd_theme
    - sphinx-build -b html docs/source static/docs
  
github-copy:
  stage: copy
  image: ubuntu:latest
  variables:
    GIT_DEPTH: 0  # Disable shallow cloning
  before_script:
    - apt-get update -y && apt-get install -y git
  script:
    - git config --global user.email "nikita.stoyanovski@gmail.com"
    - git config --global user.name "SN"
    - git remote remove origin2 || true
    - git remote add origin2 "https://skyer12322:$GH_PAT@github.com/skyer12322/FinalProject.git"
    - git push --force origin2 HEAD:develop